#ifndef __cmdline__
#define __cmdline__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -bd: run Program as a daemon in background */
  char daemonP;
  /***** -b: gpio ports connected to keys */
  char keysP;
  int *keys;
  int keysC;
  /***** -l: gpio ports for LCD */
  char lcdP;
  int *lcd;
  int lcdC;
  /***** -u: base url for mashctld state */
  char urlP;
  char* url;
  int urlC;
  /***** -dbg: enable debug output */
  char debugP;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

