Document: web20mash
Title: Debian web20mash Manual
Author: <insert document author here>
Abstract: This manual describes what web20mash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/web20mash/web20mash.sgml.gz

Format: postscript
Files: /usr/share/doc/web20mash/web20mash.ps.gz

Format: text
Files: /usr/share/doc/web20mash/web20mash.text.gz

Format: HTML
Index: /usr/share/doc/web20mash/html/index.html
Files: /usr/share/doc/web20mash/html/*.html
